name: Deploy new commit to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Azure VM via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USERNAME }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          port: 22
          script: |
            echo "🚚 ==> Pulling latest code"
            cd ~/toeic-booster/Toeic-Booster-BE
            git pull origin main

            echo "🔧 ==> Installing dependencies of laravel application"
            docker exec -it toeic_server composer install

            echo "🔧 ==> Installing dependencies of recommendation FastAPI application"
            docker exec -it toeic_recommendation pip install -r requirements.txt

            echo "🔄 ==> Restarting services"
            docker compose down
            docker compose up -d

            echo "✅ ==> Deployment finished successfully"
